[package]
name = "highlighting"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
lazy_static = "1"
syntect = { git = "https://github.com/trishume/syntect", rev = "e6f3e13266ee2d7a5127e38948559deb92652458" }
